<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 09 Sep 2016 14:16:57 +0930
 */

$conf['title'] = 'Creative Kids Wiki';
$conf['start'] = 'README';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = '2';
$conf['datadir'] = './data/wiki';
$conf['mediadir'] = './data/wiki';

// end auto-generated content
